# Generated by Django 4.0.5 on 2022-07-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Empleado')),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='zapatilla',
            fields=[
                ('idZapatilla', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID zapatilla')),
                ('modelo', models.CharField(max_length=30)),
                ('talla', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
