# Generated by Django 4.0.5 on 2022-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sucursal_ubicacion_empleados_apellidom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='genero',
            field=models.CharField(max_length=30, null=True, verbose_name='Genero'),
        ),
    ]
