# Generated by Django 4.0.5 on 2022-07-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_empleados_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fechaNacimiento',
            field=models.CharField(max_length=30, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
